# Generated by Django 6.1.1

from django.db import migrations, models


def backfill_report_names(apps, schema_editor):
    """Copy employee/project names onto the report before the FKs are removed."""
    MonthlyReportModel = apps.get_model("reports", "MonthlyReport")
    Employee = apps.get_model("reports", "Employee")
    Project = apps.get_model("reports", "Project")

    for report in MonthlyReportModel.objects.select_related("employee", "project").iterator():
        if report.employee_id is not None:
            report.employee_name = Employee.objects.get(pk=report.employee_id).name
        if report.project_id is not None:
            project = Project.objects.get(pk=report.project_id)
            report.project_name = project.name
            report.business_group = project.business_group
        report.save(update_fields=["employee_name", "project_name", "business_group"])


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="monthlyreport",
            name="unique_monthly_report_per_employee_project",
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="employee_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="project_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="monthlyreport",
            name="business_group",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(backfill_report_names, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="monthlyreport",
            name="employee",
        ),
        migrations.RemoveField(
            model_name="monthlyreport",
            name="project",
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="business_group",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="employee_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="monthlyreport",
            name="project_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="monthlyreport",
            constraint=models.UniqueConstraint(
                fields=("employee_name", "project_name", "business_group", "month", "year"),
                name="unique_monthly_report_names_per_month_year",
            ),
        ),
    ]