from django.test import TestCase

from llmops.prompt_models import PromptVersion
from reports.services.prompt_builder import (
    build_employee_summary_prompt,
    build_employee_summary_prompt_for_version,
)


VALID_REPORT_DATA = {
    "employee_name": "Ada Lovelace",
    "project_name": "Apollo",
    "business_group": "Engineering",
    "month": 9,
    "year": 2026,
    "tasks": ["Completed API implementation", "Shipped auth module"],
    "achievements": ["Named engineer of the month"],
    "courses": ["Advanced PostgreSQL"],
    "planned_holidays": ["Oct 5-9"],
    "ideas": ["Automate CI checks"],
}

PROMPT_TEMPLATE = (
    "You are an AI assistant writing a professional monthly status "
    "summary for an employee. Do not invent facts. Clearly indicate "
    "when the summary is generated by AI."
)


class PromptBuilderTests(TestCase):
    def setUp(self):
        self.prompt_version = PromptVersion.objects.create(
            feature="employee_summary",
            version="v1",
            prompt_template=PROMPT_TEMPLATE,
            is_active=True,
        )
        self.v2 = PromptVersion.objects.create(
            feature="employee_summary",
            version="v2",
            prompt_template=PROMPT_TEMPLATE.replace(
                "generated by AI", "generated by an AI assistant"
            ),
            is_active=False,
        )

    def test_build_returns_prompt_and_active_version(self):
        prompt, version = build_employee_summary_prompt(
            VALID_REPORT_DATA
        )

        self.assertEqual(version, "v1")
        self.assertIn("Ada Lovelace", prompt)
        self.assertIn("Apollo", prompt)
        self.assertIn("Engineering", prompt)
        self.assertIn("Month: 9", prompt)
        self.assertIn("Year: 2026", prompt)
        self.assertIn("Tasks Completed:", prompt)
        self.assertIn("- Completed API implementation", prompt)
        self.assertIn("Achievements / Rewards:", prompt)
        self.assertIn("Courses Taken:", prompt)
        self.assertIn("Planned Holidays:", prompt)
        self.assertIn("Ideas Submitted:", prompt)
        self.assertIn("generated by AI", prompt)

    def test_build_omits_empty_sections(self):
        payload = {**VALID_REPORT_DATA, "tasks": [], "ideas": []}

        prompt, _ = build_employee_summary_prompt(payload)

        self.assertNotIn("Tasks Completed:", prompt)
        self.assertNotIn("Ideas Submitted:", prompt)
        self.assertIn("Achievements / Rewards:", prompt)

    def test_build_uses_active_latest_version(self):
        self.v2.is_active = True
        self.v2.save()

        _, version = build_employee_summary_prompt(VALID_REPORT_DATA)

        self.assertEqual(version, "v2")

    def test_build_for_specific_version(self):
        prompt, version = build_employee_summary_prompt_for_version(
            VALID_REPORT_DATA,
            "v2",
        )

        self.assertEqual(version, "v2")
        self.assertIn("generated by an AI assistant", prompt)

    def test_build_for_missing_version_raises(self):
        with self.assertRaises(ValueError) as exc:
            build_employee_summary_prompt_for_version(
                VALID_REPORT_DATA,
                "v99",
            )

        self.assertIn("v99", str(exc.exception))

    def test_build_without_active_prompt_raises(self):
        self.prompt_version.is_active = False
        self.prompt_version.save()

        with self.assertRaises(ValueError) as exc:
            build_employee_summary_prompt(VALID_REPORT_DATA)

        self.assertIn("employee_summary", str(exc.exception))

    def test_build_sanitizes_pii_before_rendering(self):
        payload = {
            **VALID_REPORT_DATA,
            "employee_name": "Ada <ada@example.com>",
            "tasks": ["Call 123-456-7890"],
        }

        prompt, _ = build_employee_summary_prompt(payload)

        self.assertNotIn("ada@example.com", prompt)
        self.assertNotIn("123-456-7890", prompt)
        self.assertIn("[EMAIL]", prompt)
        self.assertIn("[PHONE]", prompt)

    def test_build_does_not_mutate_input(self):
        payload = {
            **VALID_REPORT_DATA,
            "employee_name": "Ada <ada@example.com>",
        }
        snapshot = {
            key: list(value) if isinstance(value, list) else value
            for key, value in payload.items()
        }

        build_employee_summary_prompt(payload)

        self.assertEqual(payload, snapshot)