from unittest import mock

from django.test import TestCase
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from llmops.cost_budget import LLMCostBudgetExceeded
from llmops.prompt_models import PromptVersion
from llmops.rate_limiter import LLMRateLimitExceeded
from reports.services.llm_service import (
    LLMConfigurationError,
    LLMResponseError,
)

VALID_FIELD_PAYLOAD = {
    "employee_name": "Ada Lovelace",
    "project_name": "Apollo",
    "business_group": "Engineering",
    "month": 9,
    "year": 2026,
    "tasks": ["Completed API implementation"],
    "achievements": [],
    "courses": [],
    "planned_holidays": [],
    "ideas": [],
}


class GenerateSummaryTypedErrorTests(APITestCase):
    def setUp(self):
        PromptVersion.objects.create(
            feature="employee_summary",
            version="v1",
            prompt_template=(
                "You are an AI assistant writing a professional monthly "
                "status summary for an employee. Do not invent facts. "
                "Clearly indicate when the summary is generated by AI."
            ),
            is_active=True,
        )

    def url(self):
        return reverse("reports:monthlyreport-generate-summary")

    def generate(self, **overrides):
        payload = {**VALID_FIELD_PAYLOAD, **overrides}
        return self.client.post(self.url(), payload, format="json")

    @mock.patch("reports.views.LLMService")
    def test_rate_limit_exceeded_returns_429(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = (
            LLMRateLimitExceeded("LLM rate limit exceeded.")
        )

        response = self.generate()

        self.assertEqual(
            response.status_code,
            status.HTTP_429_TOO_MANY_REQUESTS,
        )
        self.assertIn("detail", response.data)

    @mock.patch("reports.views.LLMService")
    def test_cost_budget_exceeded_returns_429(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = (
            LLMCostBudgetExceeded("Monthly LLM cost budget exceeded.")
        )

        response = self.generate()

        self.assertEqual(
            response.status_code,
            status.HTTP_429_TOO_MANY_REQUESTS,
        )
        self.assertIn("detail", response.data)

    @mock.patch("reports.views.LLMService")
    def test_configuration_error_returns_503_with_safe_message(
        self, mock_service_cls
    ):
        mock_service_cls.return_value.generate.side_effect = (
            LLMConfigurationError("LLM_MODEL is not configured.")
        )

        response = self.generate()

        self.assertEqual(
            response.status_code,
            status.HTTP_503_SERVICE_UNAVAILABLE,
        )
        self.assertIn("detail", response.data)
        self.assertNotIn("LLM_MODEL", response.data["detail"])

    @mock.patch("reports.views.LLMService")
    def test_response_error_returns_502_with_safe_message(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = (
            LLMResponseError("The LLM API returned HTTP 500.")
        )

        response = self.generate()

        self.assertEqual(
            response.status_code,
            status.HTTP_502_BAD_GATEWAY,
        )
        self.assertIn("detail", response.data)

    @mock.patch("reports.views.LLMService")
    def test_error_responses_never_expose_credentials(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = (
            LLMConfigurationError("LLM_API_KEY is not configured.")
        )

        response = self.generate()

        body = response.content.decode("utf-8")
        self.assertNotIn("sk-", body)
        self.assertNotIn("LLM_API_KEY", body)


class TypedErrorMappingTests(TestCase):
    """The four typed errors map to distinct expected HTTP semantics."""

    def test_errors_are_distinct_types(self):
        rate_limit = LLMRateLimitExceeded("x")
        budget = LLMCostBudgetExceeded("x")
        config = LLMConfigurationError("x")
        response = LLMResponseError("x")

        self.assertNotIsInstance(rate_limit, LLMResponseError)
        self.assertNotIsInstance(budget, LLMResponseError)
        self.assertNotIsInstance(config, LLMResponseError)
        self.assertIsInstance(response, LLMResponseError)