"""Builds the prompt for the manager monthly team report.

Only the prompt/data preparation differs from the employee summary flow;
the actual LLM call reuses :class:`reports.services.llm_service.LLMService`.
"""

from collections import defaultdict

from ..models import ReportItemType
from llmops.prompt_service import PromptVersionService

_ITEM_LABELS = {
    ReportItemType.TASK: "Tasks Completed",
    ReportItemType.ACHIEVEMENT: "Achievements / Rewards",
    ReportItemType.COURSE: "Courses Taken",
    ReportItemType.HOLIDAY: "Planned Holidays",
    ReportItemType.IDEA: "Ideas Submitted",
}

INSTRUCTIONS = """You are an assistant that writes collective monthly team reports for managers.

Write a professional monthly team report for the selected month/year using ONLY
the supplied employee report data.

Rules:
- Use ONLY the supplied employee report data. Do not invent facts.
- Do not invent achievements.
- Do not invent metrics.
- Do not invent project information.
- Do not invent business groups.
- Do not combine unrelated work as if it were one project.
- Do not attribute work to an employee unless the supplied data supports it.
- Identify major work themes across the reports.
- Summarize important accomplishments.
- Summarize learning/courses when present.
- Mention notable ideas submitted when present.
- Group related work where appropriate.
- Preserve project/business group context where useful.
- Avoid unnecessary repetition.
- Do not mention that the report was generated by AI.

Suggestions on the report structure — include a section only when there is
supporting data, otherwise omit it:
1. Overall Summary
2. Work Completed
3. Key Achievements / Rewards
4. New Learnings / Courses
5. Ideas and Improvements
6. Project / Business Group Highlights"""


def _report_block(report):
    """Render a single employee report as structured data for the prompt."""
    lines = [f"Employee: {report.employee_name}", f"Project: {report.project_name}",
             f"Business Group: {report.business_group}"]
    if report.summary:
        lines.append(f"Summary: {report.summary}")

    grouped = defaultdict(list)
    for item in report.items.all():
        grouped[item.item_type].append(item.content)

    for item_type in ReportItemType.values:
        entries = grouped.get(item_type)
        if not entries:
            continue
        lines.extend(["", f"{_ITEM_LABELS[item_type]}:"])
        lines.extend(f"- {entry}" for entry in entries)

    return "\n".join(lines)


def build_monthly_team_report_prompt(reports, month, year):
    """Build a prompt for a collective monthly team report."""

    prompt_version = PromptVersionService.get_active_prompt(
        "monthly_team_report"
    )

    if not prompt_version:
        raise ValueError(
            "No active prompt configured for monthly_team_report."
        )

    report_sections = "\n\n".join(
        f"[Employee report {index}]\n{_report_block(report)}"
        for index, report in enumerate(reports, start=1)
    )

    return (
    "\n\n".join(
        [
            prompt_version.prompt_template,
            f"Month: {month}",
            f"Year: {year}",
            "Employee reports:",
            report_sections,
        ]
    ),
    prompt_version.version,
)