"""Builds the prompt for the manager quarterly team report.

Only the prompt/data preparation differs from the employee summary flow;
the actual LLM call reuses :class:`reports.services.llm_service.LLMService`.
"""

from collections import defaultdict

from ..models import ReportItemType
from llmops.prompt_service import PromptVersionService

QUARTER_MONTHS = {
    1: (1, 2, 3),
    2: (4, 5, 6),
    3: (7, 8, 9),
    4: (10, 11, 12),
}

MONTH_NAMES = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
]

_ITEM_LABELS = {
    ReportItemType.TASK: "Tasks Completed",
    ReportItemType.ACHIEVEMENT: "Achievements / Rewards",
    ReportItemType.COURSE: "Courses Taken",
    ReportItemType.HOLIDAY: "Planned Holidays",
    ReportItemType.IDEA: "Ideas Submitted",
}

INSTRUCTIONS = """You are an assistant that writes collective quarterly team reports for managers.

Write a professional quarterly team report using ONLY the supplied employee
report data for the selected quarter/year.

Notes:
- Use ONLY the supplied employee report data. Do not invent facts.
- Do not invent achievements.
- Do not invent metrics.
- Do not invent project information.
- Do not invent business groups.
- Do not combine unrelated work as if it were one project.
- Do not attribute work to an employee unless the supplied data supports it.
- If information is unavailable, omit it rather than guessing.
- Do not invent activity for months within the quarter that have no reports.
- Identify major work themes across the reports.
- Preserve project and business group context where useful.
- Avoid unnecessary repetition.
- Do not mention that the report was generated by AI.

Report structure:
1. Executive Summary - a concise summary of the team's work during the quarter.
2. Quarter Overview - mention the selected quarter and year (e.g. Q3 2026).
3. Month-wise Highlights - organize important work across the three months of
   the quarter; only report activity for months that have data.
4. Project-wise Work - summarize documented work by project.
5. Business Group-wise Work - summarize documented work by business group.
6. Key Achievements and Rewards - summarize achievements and rewards recorded
   in the employee reports.
7. Learning and Development - summarize courses and learning activities
   recorded during the quarter.
8. Ideas Submitted - summarize ideas submitted during the quarter.
9. Planned Holidays - summarize planned holidays only when useful and based
   strictly on the supplied data.
10. Overall Quarterly Summary - a concise management-level conclusion based
    only on the reports."""


def _report_block(report):
    """Render a single employee report, including its month, for the prompt."""
    lines = [
        f"Month: {MONTH_NAMES[report.month - 1]}",
        f"Employee: {report.employee_name}",
        f"Project: {report.project_name}",
        f"Business Group: {report.business_group}",
    ]
    if report.summary:
        lines.append(f"Summary: {report.summary}")

    grouped = defaultdict(list)
    for item in report.items.all():
        grouped[item.item_type].append(item.content)

    for item_type in ReportItemType.values:
        entries = grouped.get(item_type)
        if not entries:
            continue
        lines.extend(["", f"{_ITEM_LABELS[item_type]}:"])
        lines.extend(f"- {entry}" for entry in entries)

    return "\n".join(lines)


def build_quarterly_team_report_prompt(reports, quarter, year):
    """Build a prompt for a collective quarterly team report."""

    prompt_version = PromptVersionService.get_active_prompt(
        "quarterly_team_report"
    )

    if not prompt_version:
        raise ValueError(
            "No active prompt configured for quarterly_team_report."
        )

    quarter_months = QUARTER_MONTHS[quarter]
    months_label = ", ".join(
        MONTH_NAMES[month - 1]
        for month in quarter_months
    )

    report_sections = "\n\n".join(
        f"[Employee report {index}]\n{_report_block(report)}"
        for index, report in enumerate(reports, start=1)
    )

    return (
        "\n\n".join(
            [
                prompt_version.prompt_template,
                f"Quarter: Q{quarter}",
                f"Year: {year}",
                f"Months in this quarter: {months_label}",
                "Employee reports:",
                report_sections,
            ]
        ),
        prompt_version.version,
    )