# Generated by Django 6.1.1 on 2026-09-29 04:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "request_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("feature", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("model", models.CharField(max_length=200)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                        max_length=20,
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("output_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("total_tokens", models.PositiveIntegerField(blank=True, null=True)),
                ("error_type", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["feature"], name="llmops_llmr_feature_7ac11f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="llmops_llmr_status_799761_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="llmops_llmr_created_56d8c9_idx"
                    ),
                ],
            },
        ),
    ]
