# Generated by Django 6.1.1 on 2026-09-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="input_cost",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="llmrequest",
            name="output_cost",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="llmrequest",
            name="total_cost",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="llmrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                max_length=20,
            ),
        ),
    ]
