# Generated by Django 6.1.1 on 2026-09-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmops", "0002_llmrequest_input_cost_llmrequest_output_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feature", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=50)),
                ("prompt_template", models.TextField()),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["feature"], name="llmops_prom_feature_69c86e_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="llmops_prom_is_acti_9bc64b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feature", "version"),
                        name="unique_prompt_feature_version",
                    )
                ],
            },
        ),
    ]
