# Generated by Django 6.1.1 on 2026-09-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmops", "0003_promptversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="prompt_version",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
