# Generated by Django 6.1.1 on 2026-09-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmops", "0004_llmrequest_prompt_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="trace_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
