# Generated by Django 6.1.1 on 2026-09-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmops", "0005_llmrequest_trace_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="operation",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
