# Generated by Django 6.1.1 on 2026-09-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmops", "0006_llmrequest_operation"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmrequest",
            name="error_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
