# Generated by Django 6.1.1 on 2026-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("llmops", "0007_llmrequest_error_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="LLMEvaluation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("feature", models.CharField(db_index=True, max_length=100)),
                (
                    "evaluation_type",
                    models.CharField(
                        choices=[
                            ("reference", "Reference Based"),
                            ("llm_judge", "LLM Judge"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metric", models.CharField(max_length=100)),
                ("score", models.FloatField()),
                (
                    "reference_dataset_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "evaluator_model",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
