import json
from unittest import mock

from django.test import TestCase, override_settings
from django.urls import reverse
from rest_framework import status
from rest_framework.test import APITestCase

from .models import MonthlyReport
from .services.llm_service import (
    LLMConfigurationError,
    LLMResponseError,
    LLMService,
)
from .services.prompt_builder import build_employee_summary_prompt

VALID_FIELD_PAYLOAD = {
    "employee_name": "Ada Lovelace",
    "project_name": "Apollo",
    "business_group": "Engineering",
    "month": 9,
    "year": 2026,
    "tasks": ["Completed API implementation", "Shipped auth module"],
    "achievements": ["Named engineer of the month"],
    "courses": ["Advanced PostgreSQL"],
    "planned_holidays": ["Oct 5-9"],
    "ideas": ["Automate CI checks"],
}


class MockLLMResponse:
    def __init__(self, body):
        self._body = json.dumps(body).encode("utf-8")

    def read(self):
        return self._body

    def __enter__(self):
        return self

    def __exit__(self, *exc_info):
        return False


def make_openai_body(content="Generated monthly summary."):
    return {"choices": [{"message": {"content": content}}]}


@override_settings(
    LLM_API_KEY="test-key",
    LLM_MODEL="test-model",
    LLM_BASE_URL="https://llm.example.com/v1",
)
class PromptBuilderTests(TestCase):
    def test_prompt_includes_only_provided_information(self):
        prompt = build_employee_summary_prompt(VALID_FIELD_PAYLOAD)

        self.assertIn("Ada Lovelace", prompt)
        self.assertIn("Apollo", prompt)
        self.assertIn("Engineering", prompt)
        self.assertIn("Month: 9", prompt)
        self.assertIn("Year: 2026", prompt)
        self.assertIn("- Completed API implementation", prompt)
        self.assertIn("- Named engineer of the month", prompt)
        self.assertIn("- Advanced PostgreSQL", prompt)
        self.assertIn("Ideas Submitted:", prompt)
        self.assertIn("Do not invent facts", prompt)
        self.assertIn("generated by AI", prompt)

    def test_prompt_omits_empty_sections(self):
        payload = {**VALID_FIELD_PAYLOAD, "tasks": [], "ideas": []}

        prompt = build_employee_summary_prompt(payload)

        self.assertNotIn("Tasks Completed:", prompt)
        self.assertNotIn("Ideas Submitted:", prompt)
        self.assertIn("Achievements / Rewards:", prompt)


@override_settings(
    LLM_API_KEY="test-key",
    LLM_MODEL="test-model",
    LLM_BASE_URL="https://llm.example.com/v1",
)
class LLMServiceTests(TestCase):
    def generate(self, **kwargs):
        return LLMService(**kwargs).generate("Please summarize.")

    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_generate_returns_content(self, mock_urlopen):
        mock_urlopen.return_value = MockLLMResponse(make_openai_body("Monthly summary here."))

        result = self.generate()

        self.assertEqual(result, "Monthly summary here.")

    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_generate_posts_to_chat_completions_with_expected_body(self, mock_urlopen):
        mock_urlopen.return_value = MockLLMResponse(make_openai_body("x"))

        self.generate()

        request = mock_urlopen.call_args.args[0]
        self.assertEqual(
            request.full_url, "https://llm.example.com/v1/chat/completions"
        )
        self.assertEqual(request.get_method(), "POST")
        self.assertEqual(request.get_header("Authorization"), "Bearer test-key")
        payload = json.loads(request.data)
        self.assertEqual(payload["model"], "test-model")
        self.assertEqual(payload["messages"][-1]["content"], "Please summarize.")

    def test_missing_model_raises_configuration_error(self):
        with self.assertRaises(LLMConfigurationError):
            self.generate(model="")

    @override_settings(LLM_API_KEY="", LLM_BASE_URL="https://api.openai.com/v1")
    def test_missing_api_key_on_default_provider_raises_configuration_error(self):
        with self.assertRaises(LLMConfigurationError):
            self.generate(api_key="")

    @override_settings(LLM_API_KEY="", LLM_BASE_URL="http://localhost:11434/v1")
    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_missing_api_key_on_custom_base_url_is_allowed(self, mock_urlopen):
        mock_urlopen.side_effect = __import__(
            "urllib.error", fromlist=["URLError"]
        ).URLError("Connection refused")

        with self.assertRaises(LLMResponseError):
            self.generate()

    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_http_error_raises_response_error(self, mock_urlopen):
        mock_urlopen.side_effect = __import__("urllib.error", fromlist=["HTTPError"]).HTTPError(
            "url", 500, "Server Error", {}, None
        )

        with self.assertRaises(LLMResponseError):
            self.generate()

    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_connection_error_raises_response_error(self, mock_urlopen):
        mock_urlopen.side_effect = __import__(
            "urllib.error", fromlist=["URLError"]
        ).URLError("Connection refused")

        with self.assertRaises(LLMResponseError):
            self.generate()

    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_timeout_raises_response_error(self, mock_urlopen):
        mock_urlopen.side_effect = TimeoutError("timed out")

        with self.assertRaises(LLMResponseError):
            self.generate()

    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_empty_content_raises_response_error(self, mock_urlopen):
        mock_urlopen.return_value = MockLLMResponse(make_openai_body("   "))

        with self.assertRaises(LLMResponseError):
            self.generate()

    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_empty_response_body_raises_response_error(self, mock_urlopen):
        mock_urlopen.return_value = MockLLMResponse({})

        with self.assertRaises(LLMResponseError):
            self.generate()

    @mock.patch("reports.services.llm_service.urllib.request.urlopen")
    def test_content_is_trimmed(self, mock_urlopen):
        mock_urlopen.return_value = MockLLMResponse(make_openai_body("  padded  "))

        self.assertEqual(self.generate(), "padded")


class GenerateSummaryApiTests(APITestCase):
    def url(self):
        return reverse("reports:monthlyreport-generate-summary")

    def generate(self, **overrides):
        payload = {**VALID_FIELD_PAYLOAD, **overrides}
        return self.client.post(self.url(), payload, format="json")

    @mock.patch("reports.views.LLMService")
    def test_generates_summary_from_form_data(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "AI monthly summary."

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data, {"summary": "AI monthly summary."})

    @mock.patch("reports.views.LLMService")
    def test_prompt_is_built_from_form_data(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "x"

        self.generate(tasks=["Shipped auth module"])

        prompt = mock_service_cls.return_value.generate.call_args.args[0]
        self.assertIn("Ada Lovelace", prompt)
        self.assertIn("Shipped auth module", prompt)

    @mock.patch("reports.views.LLMService")
    def test_endpoint_does_not_persist_anything(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "AI monthly summary."

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(MonthlyReport.objects.count(), 0)

    @mock.patch("reports.views.LLMService")
    def test_repeated_generation_does_not_create_duplicate_reports(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "summary v1"
        self.assertEqual(self.generate().status_code, status.HTTP_200_OK)

        mock_service_cls.return_value.generate.return_value = "summary v2"
        self.assertEqual(self.generate().status_code, status.HTTP_200_OK)

        self.assertEqual(MonthlyReport.objects.count(), 0)

    def test_missing_required_fields_are_rejected(self):
        response = self.client.post(self.url(), {"month": 9}, format="json")

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("employee_name", response.data)
        self.assertIn("project_name", response.data)
        self.assertIn("business_group", response.data)
        self.assertIn("year", response.data)
        self.assertEqual(MonthlyReport.objects.count(), 0)

    def test_invalid_month_is_rejected(self):
        response = self.generate(month=13)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("month", response.data)

    def test_invalid_year_is_rejected(self):
        response = self.generate(year=1800)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("year", response.data)

    def test_get_is_not_allowed(self):
        response = self.client.get(self.url())

        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

    @mock.patch("reports.views.LLMService")
    def test_missing_config_returns_503(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = LLMConfigurationError(
            "LLM_MODEL is not configured."
        )

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_503_SERVICE_UNAVAILABLE)
        self.assertIn("detail", response.data)
        self.assertNotIn("LLM_MODEL", response.data["detail"])

    @mock.patch("reports.views.LLMService")
    def test_llm_failure_returns_502(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = LLMResponseError(
            "The LLM API returned HTTP 500."
        )

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_502_BAD_GATEWAY)
        self.assertIn("detail", response.data)

    @mock.patch("reports.views.LLMService")
    def test_timeout_returns_502(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = LLMResponseError(
            "The LLM API could not be reached."
        )

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_502_BAD_GATEWAY)

    @mock.patch("reports.views.LLMService")
    def test_errors_never_expose_credentials(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = LLMConfigurationError(
            "LLM_API_KEY is not configured."
        )

        response = self.generate()

        body = response.content.decode("utf-8")
        self.assertNotIn("test-key", body)
        self.assertNotIn("sk-", body)