from unittest import mock

from django.urls import reverse
from llmops.prompt_models import PromptVersion
from rest_framework import status
from rest_framework.test import APITestCase

from .models import MonthlyReport, ReportItem, ReportItemType
from .services.llm_service import LLMConfigurationError, LLMResponseError
from .services.manager_report_prompt import (
    INSTRUCTIONS as MANAGER_MONTHLY_INSTRUCTIONS,
    build_monthly_team_report_prompt,
)
from .services.quarterly_report_prompt import (
    INSTRUCTIONS as MANAGER_QUARTERLY_INSTRUCTIONS,
    MONTH_NAMES,
    QUARTER_MONTHS,
    build_quarterly_team_report_prompt,
)


def create_active_prompt(feature, template, version="v1"):
    return PromptVersion.objects.create(
        feature=feature,
        version=version,
        prompt_template=template,
        is_active=True,
    )


def make_report(employee_name, project_name, business_group, month, year, summary=""):
    return MonthlyReport.objects.create(
        employee_name=employee_name,
        project_name=project_name,
        business_group=business_group,
        month=month,
        year=year,
        summary=summary,
    )


def make_item(report, item_type, content):
    return ReportItem.objects.create(report=report, item_type=item_type, content=content)


class ManagerReportPromptTests(APITestCase):
    @classmethod
    def setUpTestData(cls):
        create_active_prompt("monthly_team_report", MANAGER_MONTHLY_INSTRUCTIONS)

    def setUp(self):
        self.richa = make_report(
            "Richa Verma", "AI Platform", "DC Engineering", 9, 2026, "Shipped auth."
        )
        make_item(self.richa, ReportItemType.TASK, "Built the login flow")
        make_item(self.richa, ReportItemType.ACHIEVEMENT, "Won internal hackathon")
        self.john = make_report("John Smith", "Automation", "Cloud", 9, 2026)
        make_item(self.john, ReportItemType.COURSE, "AWS certification")

    def test_prompt_includes_full_employee_report_data(self):
        report = MonthlyReport.objects.filter(pk=self.richa.pk).prefetch_related("items")

        prompt, _ = build_monthly_team_report_prompt(report, 9, 2026)

        self.assertIn("Richa Verma", prompt)
        self.assertIn("AI Platform", prompt)
        self.assertIn("DC Engineering", prompt)
        self.assertIn("Built the login flow", prompt)
        self.assertIn("Won internal hackathon", prompt)
        self.assertIn("Shipped auth.", prompt)
        self.assertIn("Month: 9", prompt)
        self.assertIn("Year: 2026", prompt)

    def test_prompt_contains_do_not_invent_instructions(self):
        prompt, _ = build_monthly_team_report_prompt(
            MonthlyReport.objects.filter(pk=self.richa.pk), 9, 2026
        )

        for phrase in (
            "Use ONLY the supplied employee report data",
            "Do not invent achievements",
            "Do not invent metrics",
            "Do not invent project information",
            "Do not invent business groups",
            "Do not combine unrelated work",
            "Do not attribute work to an employee",
            "Do not mention that the report was generated by AI",
        ):
            self.assertIn(phrase, prompt)

    def test_prompt_contains_suggested_report_sections(self):
        prompt, _ = build_monthly_team_report_prompt(
            MonthlyReport.objects.filter(pk=self.richa.pk), 9, 2026
        )

        for section in (
            "Overall Summary",
            "Work Completed",
            "Key Achievements / Rewards",
            "New Learnings / Courses",
            "Ideas and Improvements",
            "Project / Business Group Highlights",
        ):
            self.assertIn(section, prompt)

    def test_prompt_omits_item_sections_with_no_data(self):
        prompt, _ = build_monthly_team_report_prompt(
            MonthlyReport.objects.filter(pk=self.john.pk), 9, 2026
        )

        self.assertNotIn("Built the login flow", prompt)
        self.assertNotIn("Won internal hackathon", prompt)


class ManagerReportApiTests(APITestCase):
    @classmethod
    def setUpTestData(cls):
        create_active_prompt("monthly_team_report", MANAGER_MONTHLY_INSTRUCTIONS)

    def url(self):
        return reverse("reports:manager-report-monthly-generate")

    def generate(self, month=9, year=2026):
        return self.client.post(self.url(), {"month": month, "year": year}, format="json")

    def setUp(self):
        self.richa = make_report("Richa Verma", "AI Platform", "DC Engineering", 9, 2026)
        make_item(self.richa, ReportItemType.TASK, "Built the login flow")
        self.john = make_report("John Smith", "Automation", "Cloud", 9, 2026)
        make_item(self.john, ReportItemType.COURSE, "AWS certification")

    @mock.patch("reports.views.LLMService")
    def test_generates_team_report_for_selected_month(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Team report text."

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["month"], 9)
        self.assertEqual(response.data["year"], 2026)
        self.assertEqual(response.data["reports_count"], 2)
        self.assertEqual(response.data["report"], "Team report text.")

    @mock.patch("reports.views.LLMService")
    def test_only_selected_months_reports_are_sent_to_llm(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Team report text."
        make_report("Grace Hopper", "Compiler", "Research", 8, 2026)
        make_report("Ada Lovelace", "Analytics", "Research", 9, 2025)

        self.generate()

        prompt = mock_service_cls.return_value.generate.call_args.args[0]
        self.assertIn("Richa Verma", prompt)
        self.assertIn("John Smith", prompt)
        self.assertNotIn("Grace Hopper", prompt)
        self.assertNotIn("Ada Lovelace", prompt)

    @mock.patch("reports.views.LLMService")
    def test_reports_from_other_years_are_excluded(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Team report text."
        make_report("Grace Hopper", "Compiler", "Research", 9, 2025)

        self.generate(month=9, year=2026)

        prompt = mock_service_cls.return_value.generate.call_args.args[0]
        self.assertNotIn("Grace Hopper", prompt)
        self.assertIn("Richa Verma", prompt)

    @mock.patch("reports.views.LLMService")
    def test_reports_from_other_months_are_excluded(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Team report text."
        make_report("Grace Hopper", "Compiler", "Research", 10, 2026)

        self.generate(month=9, year=2026)

        prompt = mock_service_cls.return_value.generate.call_args.args[0]
        self.assertNotIn("Grace Hopper", prompt)
        self.assertIn("Richa Verma", prompt)

    def test_no_reports_returns_appropriate_response(self):
        MonthlyReport.objects.all().delete()

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["month"], 9)
        self.assertEqual(response.data["year"], 2026)
        self.assertEqual(response.data["reports_count"], 0)
        self.assertEqual(response.data["report"], "")

    def test_no_reports_does_not_call_the_llm(self):
        MonthlyReport.objects.all().delete()

        with mock.patch("reports.views.LLMService") as mock_service_cls:
            response = self.generate()
            mock_service_cls.return_value.generate.assert_not_called()

        self.assertEqual(response.status_code, status.HTTP_200_OK)

    def test_invalid_month_is_rejected(self):
        response = self.generate(month=13)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("month", response.data)

    def test_invalid_year_is_rejected(self):
        response = self.generate(year=1800)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("year", response.data)

    def test_get_is_not_allowed(self):
        response = self.client.get(self.url())

        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

    @mock.patch("reports.views.LLMService")
    def test_llm_failure_returns_502(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = LLMResponseError(
            "The LLM API returned HTTP 500."
        )

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_502_BAD_GATEWAY)
        self.assertIn("detail", response.data)

    @mock.patch("reports.views.LLMService")
    def test_missing_config_returns_503(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = LLMConfigurationError(
            "LLM_MODEL is not configured."
        )

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_503_SERVICE_UNAVAILABLE)
        self.assertIn("detail", response.data)

    @mock.patch("reports.views.LLMService")
    def test_generated_manager_report_is_not_saved(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Team report text."

        before = list(MonthlyReport.objects.order_by("id").values_list("id", flat=True))
        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(
            list(MonthlyReport.objects.order_by("id").values_list("id", flat=True)),
            before,
        )

    @mock.patch("reports.views.LLMService")
    def test_employee_report_data_remains_unchanged(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Team report text."

        self.generate()

        self.richa.refresh_from_db()
        self.john.refresh_from_db()
        self.assertEqual(self.richa.summary, "")
        self.assertEqual(self.richa.project_name, "AI Platform")
        self.assertEqual(self.john.business_group, "Cloud")
        self.assertEqual(self.richa.items.count(), 1)
        self.assertEqual(self.john.items.count(), 1)
        self.assertEqual(ReportItem.objects.get(report=self.richa).content, "Built the login flow")


class QuarterMappingTests(APITestCase):
    def test_q1_maps_to_jan_feb_mar(self):
        self.assertEqual(QUARTER_MONTHS[1], (1, 2, 3))

    def test_q2_maps_to_apr_may_jun(self):
        self.assertEqual(QUARTER_MONTHS[2], (4, 5, 6))

    def test_q3_maps_to_jul_aug_sep(self):
        self.assertEqual(QUARTER_MONTHS[3], (7, 8, 9))

    def test_q4_maps_to_oct_nov_dec(self):
        self.assertEqual(QUARTER_MONTHS[4], (10, 11, 12))


class QuarterlyReportPromptTests(APITestCase):
    @classmethod
    def setUpTestData(cls):
        create_active_prompt("quarterly_team_report", MANAGER_QUARTERLY_INSTRUCTIONS)

    def setUp(self):
        self.richa = make_report(
            "Richa Verma", "AI Platform", "DC Engineering", 8, 2026, "Shipped auth."
        )
        make_item(self.richa, ReportItemType.TASK, "Built the login flow")
        make_item(self.richa, ReportItemType.ACHIEVEMENT, "Won internal hackathon")
        self.john = make_report("John Smith", "Automation", "Cloud", 9, 2026)
        make_item(self.john, ReportItemType.COURSE, "AWS certification")

    def test_prompt_includes_quarter_year_and_months(self):
        prompt, _ = build_quarterly_team_report_prompt(
            MonthlyReport.objects.all().prefetch_related("items"), 3, 2026
        )

        self.assertIn("Quarter: Q3", prompt)
        self.assertIn("Year: 2026", prompt)
        self.assertIn("July", prompt)
        self.assertIn("August", prompt)
        self.assertIn("September", prompt)

    def test_prompt_includes_full_employee_report_data(self):
        prompt, _ = build_quarterly_team_report_prompt(
            MonthlyReport.objects.filter(pk=self.richa.pk).prefetch_related("items"), 3, 2026
        )

        self.assertIn("Richa Verma", prompt)
        self.assertIn("AI Platform", prompt)
        self.assertIn("DC Engineering", prompt)
        self.assertIn("Built the login flow", prompt)
        self.assertIn("Won internal hackathon", prompt)
        self.assertIn("Shipped auth.", prompt)
        self.assertIn(f"Month: {MONTH_NAMES[7]}", prompt)

    def test_prompt_contains_do_not_invent_instructions(self):
        prompt, _ = build_quarterly_team_report_prompt(
            MonthlyReport.objects.filter(pk=self.richa.pk), 3, 2026
        )

        for phrase in (
            "Use ONLY the supplied employee report data",
            "Do not invent achievements",
            "Do not invent metrics",
            "Do not invent project information",
            "Do not invent business groups",
            "Do not combine unrelated work",
            "Do not attribute work to an employee",
            "Do not invent activity for months",
            "Do not mention that the report was generated by AI",
        ):
            self.assertIn(phrase, prompt)

    def test_prompt_contains_suggested_report_sections(self):
        prompt, _ = build_quarterly_team_report_prompt(
            MonthlyReport.objects.filter(pk=self.richa.pk), 3, 2026
        )

        for section in (
            "Executive Summary",
            "Quarter Overview",
            "Month-wise Highlights",
            "Project-wise Work",
            "Business Group-wise Work",
            "Key Achievements and Rewards",
            "Learning and Development",
            "Ideas Submitted",
            "Planned Holidays",
            "Overall Quarterly Summary",
        ):
            self.assertIn(section, prompt)

    def test_prompt_omits_item_sections_with_no_data(self):
        prompt, _ = build_quarterly_team_report_prompt(
            MonthlyReport.objects.filter(pk=self.john.pk), 3, 2026
        )

        self.assertNotIn("Built the login flow", prompt)
        self.assertNotIn("Won internal hackathon", prompt)


class QuarterlyReportApiTests(APITestCase):
    @classmethod
    def setUpTestData(cls):
        create_active_prompt("quarterly_team_report", MANAGER_QUARTERLY_INSTRUCTIONS)

    def url(self):
        return reverse("reports:manager-report-quarterly-generate")

    def generate(self, quarter=3, year=2026):
        return self.client.post(self.url(), {"quarter": quarter, "year": year}, format="json")

    def setUp(self):
        self.richa = make_report("Richa Verma", "AI Platform", "DC Engineering", 8, 2026)
        make_item(self.richa, ReportItemType.TASK, "Built the login flow")
        self.john = make_report("John Smith", "Automation", "Cloud", 9, 2026)
        make_item(self.john, ReportItemType.COURSE, "AWS certification")

    @mock.patch("reports.views.LLMService")
    def test_generates_quarterly_report_for_selected_quarter(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Quarterly report text."

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["year"], 2026)
        self.assertEqual(response.data["quarter"], 3)
        self.assertEqual(response.data["months"], [7, 8, 9])
        self.assertEqual(response.data["report_count"], 2)
        self.assertEqual(response.data["report"], "Quarterly report text.")

    @mock.patch("reports.views.LLMService")
    def test_only_selected_quarters_reports_are_sent_to_llm(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Quarterly report text."
        make_report("Grace Hopper", "Compiler", "Research", 6, 2026)
        make_report("Ada Lovelace", "Analytics", "Research", 8, 2025)

        self.generate(quarter=3)

        prompt = mock_service_cls.return_value.generate.call_args.args[0]
        self.assertIn("Richa Verma", prompt)
        self.assertIn("John Smith", prompt)
        self.assertNotIn("Grace Hopper", prompt)
        self.assertNotIn("Ada Lovelace", prompt)

    @mock.patch("reports.views.LLMService")
    def test_reports_from_other_years_are_excluded(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Quarterly report text."
        make_report("Grace Hopper", "Compiler", "Research", 8, 2025)

        self.generate()

        prompt = mock_service_cls.return_value.generate.call_args.args[0]
        self.assertNotIn("Grace Hopper", prompt)
        self.assertIn("Richa Verma", prompt)

    @mock.patch("reports.views.LLMService")
    def test_reports_from_other_quarters_are_excluded(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Quarterly report text."
        make_report("Grace Hopper", "Compiler", "Research", 10, 2026)

        self.generate(quarter=3)

        prompt = mock_service_cls.return_value.generate.call_args.args[0]
        self.assertNotIn("Grace Hopper", prompt)
        self.assertIn("Richa Verma", prompt)

    @mock.patch("reports.views.LLMService")
    def test_no_reports_in_quarter_returns_message_and_does_not_call_llm(self, mock_service_cls):
        MonthlyReport.objects.all().delete()

        response = self.generate(quarter=1)

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data["detail"], "No employee reports found for Q1 2026.")
        mock_service_cls.return_value.generate.assert_not_called()

    def test_invalid_quarter_is_rejected(self):
        response = self.generate(quarter=5)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("quarter", response.data)

    def test_invalid_year_is_rejected(self):
        response = self.generate(year=1800)

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)
        self.assertIn("year", response.data)

    def test_get_is_not_allowed(self):
        response = self.client.get(self.url())

        self.assertEqual(response.status_code, status.HTTP_405_METHOD_NOT_ALLOWED)

    @mock.patch("reports.views.LLMService")
    def test_llm_failure_returns_502(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = LLMResponseError(
            "The LLM API returned HTTP 500."
        )

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_502_BAD_GATEWAY)
        self.assertIn("detail", response.data)

    @mock.patch("reports.views.LLMService")
    def test_missing_config_returns_503(self, mock_service_cls):
        mock_service_cls.return_value.generate.side_effect = LLMConfigurationError(
            "LLM_MODEL is not configured."
        )

        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_503_SERVICE_UNAVAILABLE)
        self.assertIn("detail", response.data)

    @mock.patch("reports.views.LLMService")
    def test_generated_quarterly_report_is_not_saved(self, mock_service_cls):
        mock_service_cls.return_value.generate.return_value = "Quarterly report text."

        before = list(MonthlyReport.objects.order_by("id").values_list("id", flat=True))
        response = self.generate()

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(
            list(MonthlyReport.objects.order_by("id").values_list("id", flat=True)),
            before,
        )